name: medical_tourism_mgt

sdkPath: .fvm/flutter_sdk
ide:
  intellij: true

command:
  bootstrap:
    runPubGetInParallel: false

packages:
  - .
  - modules/**

scripts:
  setup:
    description: "Install necessary plug-ins and bootstrap the workspace"
    run: |
      dart pub global activate fvm && \
      fvm install $FLUTTER_VERSION && \
      fvm use $FLUTTER_VERSION && \
      dart pub global activate spider && \
      brew install lefthook && \
      lefthook install && \
      melos bootstrap && \
      fvm flutter pub run flutter_launcher_icons -f flutter_launcher_icons.yaml && \
      fvm dart run flutter_native_splash:create --path=flutter_native_splash.yaml
    env:
      FLUTTER_VERSION: 3.13.9
  run_debug:
    description: "run_debug"
    run: fvm flutter run -d chrome --web-port 5555
  pub:get:
    description: "Sync pub for all modules"
    run: melos exec -- \ fvm flutter pub get
  pub:upgrade:
    description: "Upgrade pub for all modules"
    run: melos exec -- \ fvm flutter pub upgrade --major-versions
  pod:install:
    description: "Run pod install for iOS"
    run: |
      cd ios && \
      pod install --repo-update
  pod:update:
    description: "Run pod update for iOS"
    run: |
      cd ios && \
      pod update
  build_runner:
    description: "Generate *.g.dart files on modules which depends on build_runner"
    run: melos exec --depends-on="build_runner" fvm dart run build_runner build --delete-conflicting-outputs
  fixer:
    description: "Autofix dart files with import_sorter"
    run: melos exec "lefthook run fixer"
  gen-l10n:
    description: "Generate localized strings"
    run: melos exec --scope="core_l10n" -- \ fvm flutter gen-l10n
  gen-assets:
    description: "Generate assets of images and icons"
    run: |
      melos exec --scope="core_ui" -- \ spider build && \
      melos exec --scope="core_ui" -- \ fvm flutter pub run icon_font_generator --from=assets/icons --package=core_ui --class-name=UiIcons --out-font=assets/fonts/UiIcons.ttf --out-flutter=lib/src/resources/ui_icons.dart --normalize
  gen-appicon:
    description: "Generate app icon for android and ios"
    run: |
      melos exec -c 6 --fail-fast -- \ fvm flutter pub run flutter_launcher_icons -f flutter_launcher_icons*
    packageFilters:
      scope: "medical_tourism_mgt"
  widgetbook:
    run: |
      cd modules/core_ui && \
      fvm flutter run -d chrome lib/widgetbook/widgetbook.dart


  setup_win:
    description: "Install necessary plug-ins and bootstrap the workspace"
    run: |
      dart pub global activate fvm && ^
      fvm install %FLUTTER_VERSION% && ^
      fvm use %FLUTTER_VERSION% && ^
      dart pub global activate spider && ^
      lefthook install && ^
      melos bootstrap && ^
      fvm flutter pub run flutter_launcher_icons -f flutter_launcher_icons.yaml && ^
      fvm dart run flutter_native_splash:create --path=flutter_native_splash.yaml
    env:
      FLUTTER_VERSION: 3.13.9
  build_runner_win:
    description: "Generate *.g.dart files on modules which depends on build_runner"
    run: melos exec --depends-on="build_runner" fvm dart run build_runner build --delete-conflicting-outputs
  fixer_win:
    description: "Autofix dart files with import_sorter"
    run: melos exec "lefthook run fixer"
  gen_api_win:
    description: "Generate api files"
    run: melos exec --scope="core_network" -- fvm dart run build_runner build --delete-conflicting-outputs
  gen_l10n_win:
    description: "Generate localized strings"
    run: melos exec --scope="core_l10n" -- fvm flutter gen-l10n
  gen_assets_win:
    description: "Generate assets of images and icons"
    run: |
      melos exec --scope="core_ui" -- spider build && ^
      melos exec --scope="core_ui" -- fvm flutter pub run icon_font_generator --from=assets/icons --package=core_ui --class-name=UiIcons --out-font=assets/fonts/UiIcons.ttf --out-flutter=lib/src/resources/ui_icons.dart --normalize
  gen_appicon_win: 
    description: "Generate app icon for android and ios"
    run: |
      melos exec -c 6 --fail-fast -- fvm flutter pub run flutter_launcher_icons -f flutter_launcher_icons*
    packageFilters:
      scope: "medical_tourism_mgt"
  widgetbook_win:
    run: |
      cd modules/core_ui && ^
      fvm flutter run -d chrome lib/widgetbook/widgetbook.dart
  hosting_web_dev:
    description: "hosting_web_dev"
    run: fvm flutter build web --release -t lib/main_dev.dart && firebase deploy --only hosting


  core_network:
    description: "Generate core_network"
    run: melos exec --scope="core_network" -- fvm dart run build_runner build --delete-conflicting-outputs
  data_agent:
    description: "Generate data_agent"
    run: melos exec --scope="data_agent" -- fvm dart run build_runner build --delete-conflicting-outputs
  data_auth:
    description: "Generate data_auth"
    run: melos exec --scope="data_auth" -- fvm dart run build_runner build --delete-conflicting-outputs
  data_hospital:
    description: "Generate data_hospital"
    run: melos exec --scope="data_hospital" -- fvm dart run build_runner build --delete-conflicting-outputs
  data_invoice:
    description: "Generate data_invoice"
    run: melos exec --scope="data_invoice" -- fvm dart run build_runner build --delete-conflicting-outputs
  data_medical_visa:
    description: "Generate data_medical_visa"
    run: melos exec --scope="data_medical_visa" -- fvm dart run build_runner build --delete-conflicting-outputs
  data_patient:
    description: "Generate data_patient"
    run: melos exec --scope="data_patient" -- fvm dart run build_runner build --delete-conflicting-outputs
  data_process_chart:
    description: "Generate data_process_chart"
    run: melos exec --scope="data_process_chart" -- fvm dart run build_runner build --delete-conflicting-outputs
  data_quotation:
    description: "Generate data_quotation"
    run: melos exec --scope="data_quotation" -- fvm dart run build_runner build --delete-conflicting-outputs
  data_report:
    description: "Generate data_report"
    run: melos exec --scope="data_report" -- fvm dart run build_runner build --delete-conflicting-outputs
  data_sale:
    description: "Generate data_sale"
    run: melos exec --scope="data_sale" -- fvm dart run build_runner build --delete-conflicting-outputs
  data_web_appointment:
    description: "Generate data_web_appointment"
    run: melos exec --scope="data_web_appointment" -- fvm dart run build_runner build --delete-conflicting-outputs
  feature_agent:
    description: "Generate feature_agent"
    run: melos exec --scope="feature_agent" -- fvm dart run build_runner build --delete-conflicting-outputs
  feature_auth:
    description: "Generate feature_auth"
    run: melos exec --scope="feature_auth" -- fvm dart run build_runner build --delete-conflicting-outputs
  feature_hospital:
    description: "Generate feature_hospital"
    run: melos exec --scope="feature_hospital" -- fvm dart run build_runner build --delete-conflicting-outputs
  feature_invoice:
    description: "Generate feature_invoice"
    run: melos exec --scope="feature_invoice" -- fvm dart run build_runner build --delete-conflicting-outputs
  feature_medical_visa:
    description: "Generate feature_medical_visa"
    run: melos exec --scope="feature_medical_visa" -- fvm dart run build_runner build --delete-conflicting-outputs
  feature_patient:
    description: "Generate feature_patient"
    run: melos exec --scope="feature_patient" -- fvm dart run build_runner build --delete-conflicting-outputs
  feature_process_chart:
    description: "Generate feature_process_chart"
    run: melos exec --scope="feature_process_chart" -- fvm dart run build_runner build --delete-conflicting-outputs
  feature_quotation:
    description: "Generate feature_quotation"
    run: melos exec --scope="feature_quotation" -- fvm dart run build_runner build --delete-conflicting-outputs
  feature_report:
    description: "Generate feature_report"
    run: melos exec --scope="feature_report" -- fvm dart run build_runner build --delete-conflicting-outputs
  feature_sale:
    description: "Generate feature_sale"
    run: melos exec --scope="feature_sale" -- fvm dart run build_runner build --delete-conflicting-outputs
  feature_web_appointment:
    description: "Generate feature_web_appointment"
    run: melos exec --scope="feature_web_appointment" -- fvm dart run build_runner build --delete-conflicting-outputs