name: medical_tourism_mgt
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.2.2+48

environment:
  sdk: '>=3.1.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


  # Modules Util
  base_view: 0.0.1-alpha.1
  core_l10n: 0.0.1-alpha.1
  core_network: 0.0.1-alpha.1
  core_storage: 0.0.1-alpha.1
  core_ui: 0.0.1-alpha.1
  core_utils: 0.0.1-alpha.1

  # Modules Data
  data_auth: 0.0.1-alpha.1
  data_agent: 0.0.1-alpha.1
  data_hospital: 0.0.1-alpha.1
  data_invoice: 0.0.1-alpha.1
  data_medical_visa: 0.0.1-alpha.1
  data_patient: 0.0.1-alpha.1
  data_sale: 0.0.1-alpha.1
  data_report: 0.0.1-alpha.1
  data_process_chart: 0.0.1-alpha.1
  data_web_appointment: 0.0.1-alpha.1
  data_chats: 0.0.1-alpha.1

  # Modules Feature
  feature_chats: 0.0.1-alpha.1
  feature_process_chart: 0.0.1-alpha.1
  feature_web_appointment: 0.0.1-alpha.1
  feature_agent: 0.0.1-alpha.1
  feature_auth: 0.0.1-alpha.1
  feature_hospital: 0.0.1-alpha.1
  feature_invoice: 0.0.1-alpha.1
  feature_medical_visa: 0.0.1-alpha.1
  feature_patient: 0.0.1-alpha.1
  feature_report: 0.0.1-alpha.1
  feature_sale: 0.0.1-alpha.1
  socket_chat: ^0.0.1-alpha.1

  #Pubs
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  auto_route: ^7.8.3
  retrofit: ^4.0.1
  json_annotation: ^4.8.1
  intl: ^0.18.1
  dio: ^5.8.0+1
  dio_cache_interceptor: ^3.4.2
  get_it: ^7.6.8
  injectable: ^2.4.1
  equatable: ^2.0.5
  pretty_dio_logger: ^1.3.1
  stomp_dart_client: ^1.0.2
  synchronized: ^3.1.0+1
  shared_preferences: ^2.2.1
  bot_toast: ^4.1.3
  flutter_native_splash: ^2.3.10
  data_table_2: ^2.5.10
  url_strategy: ^0.2.0
  skeletonizer: ^1.3.0
  animated_toggle_switch: ^0.8.0
  badges: ^3.1.2
  jiffy: ^6.2.1
  file_picker: ^8.0.1
  flex_color_picker: ^3.3.1
  universal_io: ^2.2.2
  http: ^1.2.2
  mask_text_input_formatter: ^2.9.0
  flutter_rating_bar: ^4.0.1
  printing: ^5.12.0
  collection: ^1.18.0
  copy_with_extension: ^5.0.4
  image: ^4.3.0
  import_sorter: ^4.6.0
  htmltopdfwidgets: ^1.0.4
  pdf: ^3.11.1
  excel: ^4.0.6
  archive: ^3.6.1
  js: ^0.6.7
  webview_flutter_web: ^0.2.3+2
  webview_flutter_platform_interface: ^2.10.0
  reactive_date_time_picker: ^4.0.0
  flutter_pdfview: ^1.4.0
  socket_io_client: ^3.0.2
  libphonenumber: ^2.0.2
  pdf_render: ^1.4.12
  flutter_cache_manager: ^3.4.1
  html: ^0.15.5
  pdfrx: ^1.0.84

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1
  melos: ^6.0.0
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  retrofit_generator: ^8.0.5
  injectable_generator: ^2.6.1
  flutter_launcher_icons: ^0.13.1
  copy_with_extension_gen: ^5.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: false
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
    
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJPRegular.ttf
        - asset: assets/fonts/NotoSansJP_Bold.ttf
          weight: 700
    - family: NotoSans_JP
      fonts:
        - asset: assets/fonts/NotoSans_JP.ttf
    - family: Noto_Sans_TC
      fonts:
        - asset: assets/fonts/Noto_Sans_TC.ttf
    - family: Noto_Sans_ZH
      fonts:
        - asset: assets/fonts/Noto_Sans_ZH.ttf
    - family: Roboto_VN
      fonts:
        - asset: assets/fonts/Roboto_VN.ttf
    - family: Open_Sans_EN
      fonts:
        - asset: assets/fonts/Open_Sans_EN.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

import_sorter:
  comments: false
  ignored_files:
    - injection.config.dart
    - \/test
    - \/lib\/generated\/
    - \/lib\/resources\/
    - \/lib\/l10n\/
