// Package imports:
import 'package:reactive_forms/reactive_forms.dart';

FormGroup treatmentForm() => FormGroup({
      'id': FormControl<String>(),
      'treatment': FormControl<bool>(),
      'treatmentInJapan': FormControl<bool>(),
      'secondOpinion': FormControl<bool>(),
      'detailedExamination': FormControl<bool>(),
      'medicalCheckup': FormControl<bool>(),
      'regenerativeMedicine': FormControl<bool>(),
      'stemCellTherapy': FormControl<bool>(),
      'immuneCellTherapy': FormControl<bool>(),
      'regenerativeOthers': FormControl<bool>(),
      'bloodPurificationTherapy': FormControl<bool>(),
      'riskInspection': FormControl<bool>(),
      'beauty': FormControl<bool>(),
      'others': FormControl<bool>(),
      'othersRemark': FormControl<String>(),
      'medicalInformationFromHomeCountry': FormControl<bool>(),
      'dicomImageData': FormControl<bool>(),
      'otherTestData': FormControl<bool>(),
      'detail': FormControl<String>(),
      'diagnosisAtHomeCountry': FormControl<String>(),
      'medicalConditionExplanation': FormControl<String>(),
      'historyOfOnset': FormControl<String>(),
      'currentTreatment': FormControl<String>(),
      'drugDetails': FormArray([
        FormGroup({
          'drugName': FormControl<String?>(),
        })
      ]),
      'currentHealthStatus': FormControl<bool>(),
      'medicalHistoryDetail': FormControl<String>(),
      'familyHistoryDetail': FormControl<String>(),
      'currentDrugAllergyDetail': FormControl<bool>(),
      'drugAllergyDetail': FormControl<String>(),
      'treatmentCosts': FormControl<String>(),
      'desiredMedicalInstitution': FormControl<bool>(),
      'desiredAreaMedicalInstitutionName': FormControl<String>(),
      'reason': FormControl<String>(),
      'desiredDateOfConsultation': FormControl<String>(),
      'scheduledPeriodOfStayInJapan': FormControl<String>(),
      'walking': FormControl<bool>(),
      'walkingDetail': FormControl<String>(),
      'sitting': FormControl<bool>(),
      'sittingDetail': FormControl<String>(),
      'meal': FormControl<bool>(),
      'mealDetail': FormControl<String>(),
      'excretion': FormControl<bool>(),
      'excretionDetail': FormControl<String>(),
      'aboutPregnancy': FormControl<String>(),
      'medicalRecord': FormControl<String>(),
    });
