name: core_ui
description: A new Flutter plugin project.
version: 0.0.1-alpha.1
publish_to: "none"

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  reactive_forms: ^14.3.0
  mask_text_input_formatter: ^2.4.0
  webview_flutter: ^4.2.2
  google_maps_flutter: ^2.4.0
  auto_route: ^7.7.0
  google_fonts: ^5.1.0
  material_design_icons_flutter: ^7.0.7296
  widgetbook: ^3.1.0
  widgetbook_annotation: ^3.0.0
  dotted_line: ^3.2.2
  qr_flutter: ^4.1.0
  bot_toast: ^4.0.4
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  reactive_pinput: ^0.9.0
  flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  widgetbook_generator: ^3.0.0
  build_runner: ^2.4.6
  icon_font_generator: ^3.2.0

flutter:

  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass

  assets:
    - assets/images/4.0x/
    - assets/images/3.0x/
    - assets/images/2.0x/
    - assets/images/1.5x/
    - assets/images/
    - assets/vectors/
