name: core_ui
description: A new Flutter plugin project.
version: 0.0.1-alpha.1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # modules
  core_utils: 0.0.1-alpha.1
  core_network: 0.0.1-alpha.1
  core_l10n: 0.0.1-alpha.1
  core_storage: 0.0.1-alpha.1
  reactive_forms: ^16.1.1
  mask_text_input_formatter: ^2.4.0
  webview_flutter: ^4.2.2
  auto_route: ^7.8.3
  google_fonts: ^6.1.0
  material_design_icons_flutter: ^7.0.7296
  dotted_line: ^3.2.2
  qr_flutter: ^4.1.0
  bot_toast: ^4.0.4
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  reactive_pinput: ^3.0.0
  flutter_speed_dial: ^7.0.0
  collection: ^1.17.2
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  icon_font_generator: ^4.0.0

flutter:

  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass

  assets:
    - assets/images/4.0x/
    - assets/images/3.0x/
    - assets/images/2.0x/
    - assets/images/1.5x/
    - assets/images/
    - assets/vectors/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJPExtraLight.ttf
          weight: 100
        - asset: assets/fonts/NotoSansJPLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansJPThin.ttf
          weight: 300
        - asset: assets/fonts/NotoSansJPRegular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansJPMedium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansJPSemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansJPBold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansJPExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansJPBlack.ttf
          weight: 900
    - family: UiIcons
      fonts:
        - asset: assets/fonts/UiIcons.ttf
