name: core_ui
description: A new Flutter plugin project.
version: 0.0.1-alpha.1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # modules
  core_utils: 0.0.1-alpha.1
  core_network: 0.0.1-alpha.1
  core_l10n: 0.0.1-alpha.1
  core_storage: 0.0.1-alpha.1
  reactive_forms: ^16.1.1
  mask_text_input_formatter: ^2.4.0
  webview_flutter: ^4.2.2
  auto_route: ^7.8.3
  google_fonts: ^6.1.0
  material_design_icons_flutter: ^7.0.7296
  dotted_line: ^3.2.2
  qr_flutter: ^4.1.0
  bot_toast: ^4.0.4
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  reactive_pinput: ^3.0.0
  flutter_speed_dial: ^7.0.0
  collection: ^1.17.2
  printing: ^5.12.0
  image: ^4.2.0
  reactive_date_time_picker: ^4.0.0

  http: ^1.2.2
  path_provider: ^2.0.15
  pdf: ^3.11.1
  import_sorter: ^4.6.0
  intl: ^0.18.1
  flutter_pdfview: ^1.4.0
  libphonenumber: ^2.0.2
  pdf_render: ^1.4.12
  flutter_cache_manager: ^3.4.1
  get_it: ^7.6.8
  html: ^0.15.5
  pdfrx: ^1.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  icon_font_generator: ^4.0.0

flutter:

  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass

  assets:
    - assets/images/4.0x/
    - assets/images/3.0x/
    - assets/images/2.0x/
    - assets/images/1.5x/
    - assets/images/
    - assets/vectors/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJPRegular.ttf
        - asset: assets/fonts/NotoSansJP_Bold.ttf
          weight: 700
    - family: NotoSans_JP
      fonts:
        - asset: assets/fonts/NotoSans_JP.ttf
    - family: Noto_Sans_TC
      fonts:
        - asset: assets/fonts/Noto_Sans_TC.ttf
    - family: Noto_Sans_ZH
      fonts:
        - asset: assets/fonts/Noto_Sans_ZH.ttf
    - family: Roboto_VN
      fonts:
        - asset: assets/fonts/Roboto_VN.ttf
    - family: Open_Sans_EN
      fonts:
        - asset: assets/fonts/Open_Sans_EN.ttf
    - family: UiIcons
      fonts:
        - asset: assets/fonts/UiIcons.ttf
