// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'basic_information_hospital_request.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

BasicInformationHospitalRequest _$BasicInformationHospitalRequestFromJson(
        Map<String, dynamic> json) =>
    BasicInformationHospitalRequest(
      id: json['_id'] as String?,
      area: json['area'] as String?,
      hospitalID: json['hospitalID'] as String?,
      hospitalNameChinese: json['hospitalNameChinese'] as String,
      hospitalNameKatakana: json['hospitalNameKatakana'] as String,
      zipCode: json['zipCode'] as String?,
      location: json['location'] as String,
      googleMap: json['googleMap'] as String?,
      phoneNumber: json['phoneNumber'] as String,
      faxNumber: json['faxNumber'] as String?,
      homepage: json['homepage'] as String?,
      supportedMenu: json['supportedMenu'] as bool?,
      healthCheckup: json['healthCheckup'] as bool?,
      treatment: json['treatment'] as bool?,
      heavyIonBeam: json['heavyIonBeam'] as bool?,
      protonBeam: json['protonBeam'] as bool?,
      regenerativeMedicine: json['regenerativeMedicine'] as bool?,
      beauty: json['beauty'] as bool?,
      phone: json['phone'] as bool?,
      fax: json['fax'] as bool?,
      mail: json['mail'] as bool?,
      line: json['line'] as bool?,
      note: json['note'] as String?,
      english: json['english'] as bool?,
      chinese: json['chinese'] as bool?,
      vietnamese: json['vietnamese'] as bool?,
      otherLanguages: json['otherLanguages'] as bool?,
      languages: json['languages'] as String?,
      onlineCheck: json['onlineCheck'] as String?,
      appointment: json['appointment'] as String?,
      cdr: json['cdr'] as bool?,
      storageUrl: json['storageUrl'] as bool?,
      viewMyPage: json['viewMyPage'] as bool?,
      mailAttachment: json['mailAttachment'] as bool?,
      loanerTablet: json['loanerTablet'] as bool?,
      jmip: json['jmip'] as bool?,
      jci: json['jci'] as bool?,
      jih: json['jih'] as bool?,
      ningenDoctor: json['ningenDoctor'] as bool?,
      japanHealth: json['japanHealth'] as bool?,
      societyRorRegenerativeMedicine:
          json['societyRorRegenerativeMedicine'] as bool?,
      osakaPrefecturalBase: json['osakaPrefecturalBase'] as bool?,
      certified: json['certified'] as bool?,
      department1: json['department1'] as String?,
      department2: json['department2'] as String?,
      shift1: json['shift1'] as String?,
      shift2: json['shift2'] as String?,
      shift1Mon: json['shift1Mon'] as String?,
      shift1Tue: json['shift1Tue'] as String?,
      shift1Wed: json['shift1Wed'] as String?,
      shift1Thu: json['shift1Thu'] as String?,
      shift1Fri: json['shift1Fri'] as String?,
      shift1Sat: json['shift1Sat'] as String?,
      shift1Sun: json['shift1Sun'] as String?,
      shift2Mon: json['shift2Mon'] as String?,
      shift2Tue: json['shift2Tue'] as String?,
      shift2Wed: json['shift2Wed'] as String?,
      shift2Thu: json['shift2Thu'] as String?,
      shift2Fri: json['shift2Fri'] as String?,
      shift2Sat: json['shift2Sat'] as String?,
      shift2Sun: json['shift2Sun'] as String?,
      memo: json['memo'] as String?,
      supportLanguageRemark: json['supportLanguageRemark'] as String?,
    );

Map<String, dynamic> _$BasicInformationHospitalRequestToJson(
        BasicInformationHospitalRequest instance) =>
    <String, dynamic>{
      '_id': instance.id,
      'area': instance.area,
      'hospitalID': instance.hospitalID,
      'hospitalNameChinese': instance.hospitalNameChinese,
      'hospitalNameKatakana': instance.hospitalNameKatakana,
      'zipCode': instance.zipCode,
      'location': instance.location,
      'googleMap': instance.googleMap,
      'phoneNumber': instance.phoneNumber,
      'faxNumber': instance.faxNumber,
      'homepage': instance.homepage,
      'supportedMenu': instance.supportedMenu,
      'healthCheckup': instance.healthCheckup,
      'treatment': instance.treatment,
      'heavyIonBeam': instance.heavyIonBeam,
      'protonBeam': instance.protonBeam,
      'regenerativeMedicine': instance.regenerativeMedicine,
      'beauty': instance.beauty,
      'phone': instance.phone,
      'fax': instance.fax,
      'mail': instance.mail,
      'line': instance.line,
      'note': instance.note,
      'english': instance.english,
      'chinese': instance.chinese,
      'vietnamese': instance.vietnamese,
      'otherLanguages': instance.otherLanguages,
      'languages': instance.languages,
      'onlineCheck': instance.onlineCheck,
      'appointment': instance.appointment,
      'cdr': instance.cdr,
      'storageUrl': instance.storageUrl,
      'viewMyPage': instance.viewMyPage,
      'mailAttachment': instance.mailAttachment,
      'loanerTablet': instance.loanerTablet,
      'jmip': instance.jmip,
      'jci': instance.jci,
      'jih': instance.jih,
      'ningenDoctor': instance.ningenDoctor,
      'japanHealth': instance.japanHealth,
      'societyRorRegenerativeMedicine': instance.societyRorRegenerativeMedicine,
      'osakaPrefecturalBase': instance.osakaPrefecturalBase,
      'certified': instance.certified,
      'department1': instance.department1,
      'department2': instance.department2,
      'shift1': instance.shift1,
      'shift2': instance.shift2,
      'shift1Mon': instance.shift1Mon,
      'shift1Tue': instance.shift1Tue,
      'shift1Wed': instance.shift1Wed,
      'shift1Thu': instance.shift1Thu,
      'shift1Fri': instance.shift1Fri,
      'shift1Sat': instance.shift1Sat,
      'shift1Sun': instance.shift1Sun,
      'shift2Mon': instance.shift2Mon,
      'shift2Tue': instance.shift2Tue,
      'shift2Wed': instance.shift2Wed,
      'shift2Thu': instance.shift2Thu,
      'shift2Fri': instance.shift2Fri,
      'shift2Sat': instance.shift2Sat,
      'shift2Sun': instance.shift2Sun,
      'memo': instance.memo,
      'supportLanguageRemark': instance.supportLanguageRemark,
    };
